server:
  port: 9000

spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/api/auth/**
        - id: taskService
          uri: lb://taskService
          predicates:
            - Path=/tasks/**
        - id: commentService
          uri: lb://commentService
          predicates:
            - Path=/comment/**
        - id: projectService
          uri: lb://projectService
          predicates:
            - Path=/projects/**
        - id: kanbanService
          uri: lb://kanbanService
          predicates:
            - Path=/kanban/**
        - id: notificationService
          uri: lb://notificationService
          predicates:
            - Path=/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

# Set application to run as reactive
main:
  web-application-type: reactive
